vault_address: "https://vault.example.com"
token_variable: VAULT_TOKEN
circleci:
- name: FairwindsOps/vault-token-injector
  vault_role: repo-vault-token-injector
tfcloud:
- workspace: SomeWorkspaceID
  vault_role: some-vault-role