# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11

jobs:
  getvaultenv:
    executor: rok8s/ci-images
    steps:
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - run: echo "${FAIRWINDS_QUAY_USER}"
  test:
    working_directory: /go/src/github.com/fairwindsops/vault-token-injector

    docker:
      - image: circleci/golang:1.16-buster
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download && go mod verify
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

workflows:
  version: 2
  test:
    jobs:
      - getvaultenv:
          filters:
            branches:
              only: sudermanjr/vaultenvci
            tags:
              only: /.*/
      - test:
          requires:
            - getvaultenv
          filters:
            branches:
              only: sudermanjr/vaultenvci
            tags:
              only: /.*/
