# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11

references:
  install_vault: &install_vault
    run:
      name: install hashicorp vault
      command: |
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.12.4/vault_1.12.4_linux_amd64.zip
        unzip vault_1.12.4_linux_amd64.zip
        mv vault /usr/bin/vault
        apk --update add yq
jobs:
  test:
    working_directory: /home/circleci/go/src/github.com/fairwindsops/vault-token-injector
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - run:
          name: Go Mod
          command: go mod download && go mod verify
      - run:
          name: Run Tests
          command: |
            go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - store_test_results:
          path: /tmp/test_results
  release:
    docker:
      - image: goreleaser/goreleaser:v2.3.2
    resource_class: large
    shell: /bin/bash
    steps:
      - checkout
      - *install_vault
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - setup_remote_docker
      - run:
          name: docker login
          command: |
            docker login -u _json_key -p "$(echo $GCP_ARTIFACTREADWRITE_JSON_KEY | base64 -d)" us-docker.pkg.dev
      - run: echo 'export GORELEASER_CURRENT_TAG="${CIRCLE_TAG}"' >> $BASH_ENV
      - run: goreleaser
  snapshot:
    docker:
      - image: goreleaser/goreleaser:v2.3.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Goreleaser Snapshot
          command: goreleaser --snapshot --skip=sign
      - store_artifacts:
          path: dist
          destination: snapshot
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
