# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11

references:
jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/vault-token-injector
    docker:
      - image: circleci/golang:1.16-buster
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Go Mod
          command: go mod download && go mod verify
      - run:
          name: Run Tests
          command: |
            go test -v ./... -coverprofile=coverage.txt -covermode=atomic
            go get -u github.com/jstemmer/go-junit-report
            mkdir -p /tmp/test_results/junit
            go test -v ./... -count 5 2>&1 | go-junit-report > /tmp/test_results/junit/report.xml
      - store_test_results:
          path: /tmp/test_results
  release:
    docker:
      - image: goreleaser/goreleaser:v0.174.2 
    steps:
      - checkout
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - setup_remote_docker
      - rok8s/docker_login:
          username: ${FAIRWINDS_QUAY_USER}
          password-variable: FAIRWINDS_QUAY_TOKEN
      - run:
          name: Goreleaser
          command: |
            source ${BASH_ENV}
            goreleaser
  snapshot:
    docker:
      - image: goreleaser/goreleaser:v0.174.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Goreleaser Snapshot
          command: goreleaser --snapshot
      - store_artifacts:
          path: dist
          destination: snapshot
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
